# Generated by Django 3.0.3 on 2021-04-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField(default=0)),
                ('book_name', models.CharField(default='', max_length=500)),
                ('authorname', models.CharField(default='', max_length=500)),
                ('authorsmark', models.CharField(default='', max_length=10)),
                ('subject', models.CharField(default='', max_length=50)),
                ('copy_no', models.IntegerField(default=0)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('publisher_name', models.CharField(default='', max_length=200)),
                ('date_of_pub', models.DateTimeField(default=2021)),
                ('date_of_acc', models.DateTimeField(default=2021)),
                ('source', models.CharField(default='', max_length=50)),
                ('bill_no', models.CharField(default='', max_length=50)),
                ('date_of_bill', models.DateTimeField(default=2021)),
                ('price', models.IntegerField(default=0)),
                ('cd', models.BooleanField(default=False)),
            ],
        ),
    ]
