# Generated by Django 3.0.3 on 2021-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='acc_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
