# Generated by Django 3.0.3 on 2021-05-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksTable',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
