# Generated by Django 3.0.3 on 2021-04-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0002_auto_20210414_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='date_of_acc',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date_of_bill',
        ),
        migrations.RemoveField(
            model_name='books',
            name='date_of_pub',
        ),
    ]
