# Generated by Django 3.0.3 on 2021-05-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books_Title', '0002_auto_20210526_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=100)),
                ('total_book_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.IntegerField(default=0)),
                ('student_id', models.CharField(default='', max_length=20)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books_Title.Title')),
            ],
        ),
    ]
