# Generated by Django 3.0.3 on 2021-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books_Title', '0003_books_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='acc_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='last_used',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
